export enum ActionTypes {
  TOGGLE_DIRECTION = "playState/TOGGLE_DIRECTION",
  UPDATE_COMBO = "playState/UPDATE_COMBO",
  SETUP_INTERMEDIATE_RESULT = "playState/SETUP_INTERMEDIATE_RESULT",
  RESET_INTERMEDIATE_RESULT = "playState/RESET_INTERMEDIATE_RESULT",
  TOGGLE_SOUND = "playState/TOGGLE_SOUND",
}
